name = "ajshare"
main = "worker.js"
compatibility_date = "2024-04-03"

[assets]
directory = "./public"

[durable_objects]
bindings = [
  { name = "ROOM_DO", class_name = "RoomDO" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDO"]
